import sqlite3
import random
import hashlib
from datetime import date, timedelta, datetime, time
from pathlib import Path

# This file was initially generated by Gemini.
# Feel free to modify or extend the code as needed.


# database file path
BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "student_wellbeing_db.sqlite3"

print(f"🌰 Seeding Database at: 👉 {DB_PATH}")

def get_connection():
    return sqlite3.connect(DB_PATH)

# hashing utility
def hash_password(password):
    return hashlib.sha256(password.encode()).hexdigest()

# random datetime generator within a day
def random_dt(base_date):
    hour = random.randint(9, 17)
    minute = random.randint(0, 59)
    return datetime.combine(base_date, time(hour, minute))

# --- 2. preset data ---
MODULES = [
    ("CS101", "Intro to Programming"),
    ("CS102", "Advanced Python"),
    ("DS201", "Data Analysis Fundamentals"),
    ("AI301", "Machine Learning Basics"),
    ("ET101", "Ethics in Technology"),
    ("UX201", "User Experience Design")
]

STAFF = [
    ("EMP0001", "Alice Admin", "ADMIN"),
    ("EMP0002", "Bob Wellbeing", "WELLBEING_OFFICER"),
    ("EMP0003", "Charlie Code", "COURSE_DIRECTOR"), 
    ("EMP0004", "Diana Data", "COURSE_DIRECTOR"),
    ("EMP0005", "Evan Ethics", "COURSE_DIRECTOR")
]

TEACHER_ASSIGNMENTS = {
    "EMP0003": ["CS101", "CS102"],
    "EMP0004": ["DS201", "AI301"],
    "EMP0005": ["ET101", "UX201"]
}

# --- Seed Function ---
def seed_data():
    conn = get_connection()
    cur = conn.cursor()

    print("🧹 Cleaning old data...")
    tables = ["audit_log", "submission", "attendance", "wellbeing_record", "alert", "enrollment", "teaching_assignment", "assessment", "student", "module", "user", "retention_rule"]
    for t in tables:
        try: cur.execute(f"DELETE FROM {t}")
        except: pass
    try: cur.execute("DELETE FROM sqlite_sequence")
    except: pass

    # ----------------------------------------------------
    # A modules & Staff
    # ----------------------------------------------------
    print("✨ Creating Modules & Staff...")
    for code, title in MODULES:
        cur.execute("INSERT INTO module (module_code, title) VALUES (?, ?)", (code, title))
        cur.execute("INSERT INTO audit_log (user_id, action, details, timestamp) VALUES (?, ?, ?, ?)",
                    ("SYSTEM", "CREATE_MODULE", f"Created module {code}", datetime.now()))

    default_pw = hash_password("password123")
    for emp_id, name, role in STAFF:
        first, last = name.split(" ")
        cur.execute("INSERT INTO user (user_id, first_name, lastname, password_hash, role) VALUES (?, ?, ?, ?, ?)", 
                    (emp_id, first, last, default_pw, role))
        
        if emp_id in TEACHER_ASSIGNMENTS:
            for mod in TEACHER_ASSIGNMENTS[emp_id]:
                cur.execute("INSERT INTO teaching_assignment (user_id, module_code) VALUES (?, ?)", (emp_id, mod))

    # ----------------------------------------------------
    # B. Students & Enrollments
    # ----------------------------------------------------
    print("Creating 50 Students (Random Enrollment)...")
    active_students = []
    all_module_codes = [m[0] for m in MODULES]
    reg_date = date.today() - timedelta(days=95)

    for i in range(1, 51):
        sid = f"STU{i:04d}"
        if i <= 35: profile = "HIGH"
        elif i <= 45: profile = "AVG"
        else: profile = "RISK"
        
        cur.execute("INSERT INTO student (student_id, first_name, lastname, email, password, year) VALUES (?, ?, ?, ?, ?, ?)", 
                    (sid, f"Student{i}", "Active", f"stu{i}@uni.ac.uk", default_pw, 2025))
        
        # AUDIT LOG
        cur.execute("INSERT INTO audit_log (user_id, action, details, timestamp) VALUES (?, ?, ?, ?)",
                    ("EMP0001", "REGISTER_STUDENT", f"Registered new student {sid}", random_dt(reg_date)))
        
        # Pick 1-2 modules randomly
        num_courses = random.randint(1, 2)
        my_courses = random.sample(all_module_codes, num_courses)
        for code in my_courses:
            cur.execute("INSERT INTO enrollment (student_id, module_code) VALUES (?, ?)", (sid, code))
            
        active_students.append({"id": sid, "profile": profile, "enrolled_modules": my_courses})

    # ----------------------------------------------------
    # C. Historical Alerts for Graduated Students
    # ----------------------------------------------------
    print("🕰️ Generating Ancient History...")
    for i in range(90, 100):
        sid = f"STU{i:04d}"
        cur.execute("INSERT INTO student (student_id, first_name, lastname, email, password, year) VALUES (?, ?, ?, ?, ?, ?)", 
                    (sid, f"OldGrad{i}", "Archived", f"old{i}@uni.ac.uk", default_pw, 2018))

    old_date = date.today() - timedelta(days=730)
    for i in range(20):
        target_stu = active_students[i % len(active_students)]["id"]
        cur.execute("INSERT INTO alert (student_id, alert_type, reason, created_at, resolved) VALUES (?, 'OLD_ISSUE', 'Ancient alert', ?, 1)", (target_stu, old_date))

    # ----------------------------------------------------
    # D. Assessments, Attendance, Wellbeing, Submissions & Audit Logs
    # ----------------------------------------------------
    print("🚀 Generating Timeline (Attendance, Wellbeing, Grades, Logs)...")
    
    end_date = date.today()
    start_date = end_date - timedelta(days=90)
    midterm_date = end_date - timedelta(days=45)
    final_date = end_date - timedelta(days=10)
    current_date = start_date
    
    # Assessment Map
    assessment_map = {} # { 'CS101': {'mid': 1, 'fin': 2} }
    
    for code, _ in MODULES:
        cur.execute("INSERT INTO assessment (module_code, title, due_date, weight) VALUES (?, ?, ?, ?)",
                    (code, f"{code} Midterm", midterm_date, 40))
        mid_id = cur.lastrowid
        # Audit Log
        cur.execute("INSERT INTO audit_log (user_id, action, details, timestamp) VALUES (?, ?, ?, ?)",
                    ("EMP0003", "CREATE_ASSESSMENT", f"Published {code} Midterm", random_dt(start_date)))

        cur.execute("INSERT INTO assessment (module_code, title, due_date, weight) VALUES (?, ?, ?, ?)",
                    (code, f"{code} Final Project", final_date, 60))
        fin_id = cur.lastrowid
        # Audit Log
        cur.execute("INSERT INTO audit_log (user_id, action, details, timestamp) VALUES (?, ?, ?, ?)",
                    ("EMP0003", "CREATE_ASSESSMENT", f"Published {code} Final", random_dt(start_date)))
        
        assessment_map[code] = {'mid': mid_id, 'fin': fin_id}

    while current_date <= end_date:
        is_midterm_grading_day = (current_date == midterm_date + timedelta(days=2))
        is_final_grading_day = (current_date == final_date + timedelta(days=2))
        
        # 1. Attendance
        if current_date.weekday() < 5:
            for stu in active_students:
                for mod_code in stu["enrolled_modules"]:
                    prob = random.random()
                    status = "PRESENT"
                    if stu["profile"] == "RISK" and prob > 0.7: status = "ABSENT"
                    elif stu["profile"] == "AVG" and prob > 0.95: status = "ABSENT"
                    
                    cur.execute("INSERT INTO attendance (student_id, session_date, session_id, status) VALUES (?, ?, ?, ?)", 
                                (stu["id"], current_date, mod_code, status))
        
        # 2. Wellbeing
        if current_date.weekday() == 0:
            for stu in active_students:
                stress = 3
                if stu["profile"] == "RISK": stress = random.randint(4, 5)
                cur.execute("INSERT INTO wellbeing_record (student_id, week_start, stress_level, sleep_hours, source_type) VALUES (?, ?, ?, ?, 'survey')", 
                            (stu["id"], current_date, stress, 7.0))
                
                if stu["profile"] == "RISK" and random.random() > 0.8:
                    cur.execute("INSERT INTO alert (student_id, alert_type, reason, created_at, resolved) VALUES (?, 'HIGH_STRESS', 'Stress critical', ?, 0)", 
                                (stu["id"], current_date))
                    # [AUDIT]
                    cur.execute("INSERT INTO audit_log (user_id, action, details, timestamp) VALUES (?, ?, ?, ?)",
                                ("SYSTEM", "RAISE_ALERT", f"Auto-alert for {stu['id']}", random_dt(current_date)))

        # 3. Marking Submissions
        if is_midterm_grading_day or is_final_grading_day:
            exam_type = 'mid' if is_midterm_grading_day else 'fin'
            for stu in active_students:
                for mod_code in stu["enrolled_modules"]:
                    assess_id = assessment_map[mod_code][exam_type]

                    # Determine mark based on profile
                    if stu["profile"] == "HIGH": base = 85
                    elif stu["profile"] == "AVG": base = 65
                    else: base = 45
                    mark = min(100, max(0, base + random.randint(-10, 10)))
                    
                    status = "SUBMITTED"
                    if exam_type == 'fin' and stu["profile"] == "RISK" and random.random() > 0.7:
                        status = "MISSING"
                        mark = 0
                    
                    cur.execute("INSERT INTO submission (student_id, assessment_id, submitted_at, status, mark) VALUES (?, ?, ?, ?, ?)", 
                                (stu["id"], assess_id, datetime.now(), status, mark))
                    
                    # Audit Log
                    if random.random() > 0.95: # simulate re-grade requests
                        cur.execute("INSERT INTO audit_log (user_id, action, details, timestamp) VALUES (?, ?, ?, ?)",
                                    ("EMP0003", "SUBMIT_GRADE", f"Graded {stu['id']} on Assessment {assess_id}", random_dt(current_date)))

        current_date += timedelta(days=1)

    # F. Retention
    print("🚀 Initializing Rules...")
    cur.execute("INSERT OR IGNORE INTO retention_rule (rule_id, data_type, retention_months, is_active) VALUES (1, 'RESOLVED_ALERTS', 12, 1)")
    cur.execute("INSERT OR IGNORE INTO retention_rule (rule_id, data_type, retention_months, is_active) VALUES (2, 'GRADUATED_STUDENTS', 48, 1)")
    cur.execute("INSERT INTO audit_log (user_id, action, details, timestamp) VALUES (?, ?, ?, ?)",
                ("EMP0001", "UPDATE_RULE", "Initialized retention policies", datetime.now()))

    conn.commit()
    conn.close()
    print("✅ Database Seeded Successfully! (Assessments & Audit Logs populated)")

if __name__ == "__main__":
    seed_data()