"""
Tests for WellbeingRepository class.
Tests persistence, updates, deletions, and retrieval of wellbeing records.
"""

import pytest
from datetime import date
from unittest.mock import Mock, patch, ANY

from src.Student_Wellbeing_App.core.models.WellbeingRecord import WellbeingRecord
from src.Student_Wellbeing_App.core.repositories.WellbeingRepository import WellbeingRepository


class TestWellbeingRepository:
    """Test suite for WellbeingRepository database operations."""

    @pytest.fixture
    def mock_db(self):
        """
        Fixture to mock the database connection and cursor.
        Returns a tuple of (mock_connection, mock_cursor).
        """
        with patch('src.Student_Wellbeing_App.core.repositories.WellbeingRepository.get_db_connection') as mock_connect:
            mock_conn = Mock()
            mock_cursor = Mock()
            
            mock_connect.return_value = mock_conn
            mock_conn.cursor.return_value = mock_cursor
            
            # Setup lastrowid default
            mock_cursor.lastrowid = 1
            
            yield mock_conn, mock_cursor

    def test_upsert_existing_record_updates(self, mock_db):
        """
        Verify upsert performs an UPDATE when a record exists for student+week.
        """
        mock_conn, mock_cursor = mock_db
        
        # Mock finding an existing record (ID = 50)
        mock_cursor.fetchone.return_value = (50,)
        
        repo = WellbeingRepository()
        record = WellbeingRecord(
            record_id=0, # Placeholder
            student_id="S123",
            week_start=date(2025, 1, 1),
            stress_level=4,
            sleep_hours=6.5,
            source_type="survey"
        )

        result_id = repo.upsert(record)

        # Assertions
        assert result_id == 50
        
        # Verify SELECT check was called
        select_call = mock_cursor.execute.call_args_list[0]
        assert "SELECT record_id" in select_call[0][0]
        assert select_call[0][1] == ("S123", date(2025, 1, 1))
        
        # Verify UPDATE was called (not INSERT)
        update_call = mock_cursor.execute.call_args_list[1]
        sql = update_call[0][0]
        params = update_call[0][1]
        
        assert "UPDATE wellbeing_record" in sql
        assert "INSERT" not in sql
        assert params == (4, 6.5, 50) # stress, sleep, existing_id
        
        mock_conn.commit.assert_called_once()
        mock_conn.close.assert_called_once()

    def test_upsert_new_record_inserts(self, mock_db):
        """
        Verify upsert performs an INSERT when no record exists for student+week.
        """
        mock_conn, mock_cursor = mock_db
        
        # Mock NOT finding a record
        mock_cursor.fetchone.return_value = None
        # Mock the new ID generated by DB
        mock_cursor.lastrowid = 101
        
        repo = WellbeingRepository()
        record = WellbeingRecord(
            record_id=0,
            student_id="S123",
            week_start=date(2025, 1, 1),
            stress_level=2,
            sleep_hours=8.0,
            source_type="manual"
        )

        result_id = repo.upsert(record)

        # Assertions
        assert result_id == 101
        
        # Verify INSERT was called
        # Call 0 is SELECT, Call 1 is INSERT
        insert_call = mock_cursor.execute.call_args_list[1]
        sql = insert_call[0][0]
        params = insert_call[0][1]
        
        assert "INSERT INTO wellbeing_record" in sql
        assert params == ("S123", date(2025, 1, 1), 2, 8.0, "manual")
        
        mock_conn.commit.assert_called_once()

    def test_upsert_handles_exception(self, mock_db):
        """Verify upsert closes connection even if DB error occurs."""
        mock_conn, mock_cursor = mock_db
        
        # Simulate DB error on execute
        mock_cursor.execute.side_effect = Exception("Database connection failed")
        
        repo = WellbeingRepository()
        record = WellbeingRecord(0, "S1", date.today(), 1, 1, "test")

        with pytest.raises(Exception) as excinfo:
            repo.upsert(record)
        
        assert "Database connection failed" in str(excinfo.value)
        # Ensure cleanup happened
        mock_cursor.close.assert_called()
        mock_conn.close.assert_called()

    def test_update_by_id(self, mock_db):
        """Verify direct update by ID works correctly."""
        mock_conn, _ = mock_db
        
        repo = WellbeingRepository()
        repo.update_by_id(record_id=99, stress=5, sleep=4.5)
        
        # update_by_id calls conn.execute directly, not cursor.execute
        mock_conn.execute.assert_called_once()
        call_args = mock_conn.execute.call_args
        
        sql = call_args[0][0]
        params = call_args[0][1]
        
        assert "UPDATE wellbeing_record" in sql
        assert params == (5, 4.5, 99)
        mock_conn.commit.assert_called_once()
        mock_conn.close.assert_called_once()

    def test_delete_by_id(self, mock_db):
        """Verify deletion by ID."""
        mock_conn, _ = mock_db
        
        repo = WellbeingRepository()
        repo.delete_by_id(record_id=77)
        
        mock_conn.execute.assert_called_once()
        call_args = mock_conn.execute.call_args
        
        assert "DELETE FROM wellbeing_record" in call_args[0][0]
        assert call_args[0][1] == (77,)
        mock_conn.commit.assert_called_once()
        mock_conn.close.assert_called_once()

    def test_get_by_student(self, mock_db):
        """Verify retrieval maps DB rows to WellbeingRecord objects."""
        mock_conn, mock_cursor = mock_db
        
        # Mock DB data
        # Row format: record_id, student_id, week_start, stress_level, sleep_hours, source_type
        mock_rows = [
            (10, "S100", date(2025, 1, 8), 3, 7.5, "survey"),
            (11, "S100", date(2025, 1, 1), 4, 6.0, "manual"),
        ]
        mock_cursor.fetchall.return_value = mock_rows
        
        repo = WellbeingRepository()
        results = repo.get_by_student("S100")
        
        assert len(results) == 2
        
        # Verify first record mapping
        r1 = results[0]
        assert isinstance(r1, WellbeingRecord)
        assert r1.record_id == 10
        assert r1.student_id == "S100"
        assert r1.week_start == date(2025, 1, 8)
        assert r1.stress_level == 3
        assert r1.sleep_hours == 7.5
        assert r1.source_type == "survey"

        # Verify SQL execution
        mock_cursor.execute.assert_called_with(
            ANY, # SQL string
            ("S100",)
        )
        assert "ORDER BY week_start DESC" in mock_cursor.execute.call_args[0][0]
